version: '3.8'

services:
  db:
    build: .
    container_name: autogestion_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: autogestion
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - autogestion_network

volumes:
  db_data:

networks:
  autogestion_network:
